cd3_workflows:
  create_resources:
    enabled: bool
    validate_cd3: bool
    operations: [Optional({Optional('main_option'): str, Optional('sub_option'): str, Optional('sub_child_option'): str})]
  export_resources:
    enabled: bool
    validate_cd3: bool
    operations: [Optional({Optional('main_option'): str, Optional('sub_option'): str, Optional('sub_child_option'): str})]
