cd3_workflows:
  create_resources:
    enabled: true
    validate_cd3: false
    operations:
      - main_option: Identity
        sub_options: ["Add/Modify/Delete Compartments"]
  export_resources:
    enabled: false
    validate_cd3: false
    operations: []
