$schema: http://json-schema.org/draft-07/schema#
$id: urn:cd3:config-schema
title: CD3 Workflow Configuration Schema
description: Schema for validating config.yaml used in CD3 E2E Testing workflow
type: object
required: [cd3_workflows]
properties:
  cd3_workflows:
    type: object
    required: [create_resources, export_resources]
    properties:
      create_resources:
        $ref: '#/definitions/workflow'
      export_resources:
        $ref: '#/definitions/workflow'
    additionalProperties: false
definitions:
  workflow:
    type: object
    required: [enabled, validate_cd3, operations]
    properties:
      enabled:
        type: boolean
        description: Whether the workflow is enabled
      validate_cd3:
        type: boolean
        description: Whether to validate CD3 before execution
      operations:
        type: array
        description: List of operations to perform in the workflow
        items:
          type: object
          required: [main_option, sub_option, sub_child_option]
          properties:
            main_option:
              type: string
              enum: [Identity, Governance, Cost Management]
              description: Main operation category
            sub_option:
              type: string
              description: Sub-operation (can be empty; must be valid for main_option)
            sub_child_option:
              type: string
              description: Child sub-operation (can be empty; must be valid for sub_option)
          additionalProperties: false
      available_options:
        type: array
        description: Optional list of valid options for main_option, sub_option, and sub_child_option
        items:
          type: object
          required: [main_option, sub_options]
          properties:
            main_option:
              type: string
              enum: [Identity, Governance, Cost Management]
            sub_options:
              type: array
              items:
                type: string
          additionalProperties: false
    additionalProperties: false
additionalProperties: false
