cd3_workflows:
  create_resources:
    enabled: true
    validate_cd3: false
    operations:
      - main_option: compute
        sub_option: instance
        sub_child_option: standard
  export_resources:
    enabled: false
    validate_cd3: false
    operations: []
