cd3_workflows:
 create_resources:
    enabled: false
    validate_cd3: false
 export_resources:
    enabled: true
    validate_cd3: false
    filters:
      regions: ["phoenix"]
      compartment_ids: ["Ulag"]
    operations:
      - main_option: Export All OCI Resources
        sub_options: []
