name: Start CD3 Workflow

on:
  workflow_dispatch:
    inputs:
      workflow_type:
        description: 'Select workflow type'
        required: true
        type: choice
        options:
          - create_resources
          - export_resources
        default: create_resources
      prefix:
        description: 'Custom prefix for tenancy config (e.g., test-123)'
        required: false
        type: string
      region:
        description: 'OCI region for create_resources (e.g., us-phoenix-1)'
        required: false
        default: 'us-phoenix-1'
        type: string
      export_regions:
        description: 'Comma-separated regions to export (e.g., us-phoenix-1,us-ashburn-1)'
        required: false
        type: string
      export_compartments:
        description: 'Comma-separated compartments to export (e.g., comp_name1,comp_name2)'
        required: false
        type: string
      export_tags:
        description: 'Comma-separated tags to export (e.g., TagNameSpace.TagKey1=TagValue1)'
        required: false
        type: string
      verify_resources:
        description: 'Verify created resources'
        required: false
        type: boolean
        default: false

jobs:
  Trigger_Main_Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger E2E Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_TYPE="${{ github.event.inputs.workflow_type }}"
          PAYLOAD=$(jq -n \
            --arg ref "${{ github.ref }}" \
            --arg prefix "${{ github.event.inputs.prefix }}" \
            --arg region "${{ github.event.inputs.region }}" \
            --arg export_regions "${{ github.event.inputs.export_regions }}" \
            --arg export_compartments "${{ github.event.inputs.export_compartments }}" \
            --arg export_tags "${{ github.event.inputs.export_tags }}" \
            --arg verify_resources "${{ github.event.inputs.verify_resources }}" \
            --arg workflow_type "$WORKFLOW_TYPE" \
            '{
              ref: $ref,
              inputs: {
                prefix: $prefix,
                region: $region,
                export_regions: $export_regions,
                export_compartments: $export_compartments,
                export_tags: $export_tags,
                verify_resources: $verify_resources,
                workflow_type: $workflow_type
              }
            }')
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/e2e.yaml/dispatches" \
            -d "$PAYLOAD"
